# Authors: Aaron Graham (aaron.graham@unb.ca, aarongraham9@gmail.com) and
#          Jean-Philippe Legault (jlegault@unb.ca, jeanphilippe.legault@gmail.com)
#           for the Centre for Advanced Studies - Atlantic (CAS-Atlantic) at the
#            Univerity of New Brunswick in Fredericton, New Brunswick, Canada

["ElapsedTime"]
	regex = "Elapsed Time: (\d+[.]\d+) Seconds"

["CPU"]
	regex = "CPU: (\d+([.]\d+)?)%"

["MaxMemory"]
	regex = "Max Memory: (\d+([.]\d+)?) KiB"

["AvgMemory"]
	regex = "Average Memory: (\d+([.]\d+)?) KiB"

["MinorPF"]
	regex = "Minor PF: (\d+([.]\d+)?)"

["MajorPF"]
	regex = "Major PF: (\d+([.]\d+)?)"

["CtxSwitch"]
	regex = "Context Switch: (\d+([.]\d+)?).*"

["exit"]
	regex = "Program Exit Code: ([0-9]+)"
