# Authors: Aaron Graham (aaron.graham@unb.ca, aarongraham9@gmail.com) and
#          Jean-Philippe Legault (jlegault@unb.ca, jeanphilippe.legault@gmail.com)
#           for the Centre for Advanced Studies - Atlantic (CAS-Atlantic) at the
#            Univerity of New Brunswick in Fredericton, New Brunswick, Canada

[DEFAULT]
    auto-hide = false
    default = -1
    # hide all the values if they match their default
    hide-if = ${default}

["Core"]
	regex = "-- CPU_TYPE: (.*)"
	default = "n/a"
	key = true

["Benchmark"]
	regex = "-- BENCHMARK_NAME: (.*)"
	default = "n/a"
	key = true

["Vm"]
	regex = "-- VM: (.*)"
	default = "n/a"
	key = true

["Name"]
	regex = [
		"===== DaCapo 9.12-MR1 ([^\.]*).* starting =====",
		"====== ([^ \t\.]*).* iteration 0 started ======",
		"[Bb]enchmark[s]?: ([^\.]*).*"
		]
	default = "n/a"
	key = true

["SubName"]
	regex = [
		"===== DaCapo 9.12-MR1 [^\.]*[\.](.*) starting =====",
		"====== [^ \t\.][\.]([^ \t]*) iteration 0 started ======",
		"[Bb]enchmark[s]?: [^\.]*[\.](.*)"
		]
	default = "n/a"
	key = true

#include parse_time.toml
